"""Initial schema: users, sessions, messages, audit_events

Revision ID: a5e8420ede10
Revises: 
Create Date: 2026-02-09 18:56:56.874992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e8420ede10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('personality_id', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created_at', 'audit_events', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_audit_event_type', 'audit_events', ['event_type'], unique=False)
    op.create_index('idx_audit_request_id', 'audit_events', ['request_id'], unique=False)
    op.create_index('idx_audit_user_id', 'audit_events', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system', 'tool')", name='chk_message_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_created_at', 'messages', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_messages_session_created', 'messages', ['session_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_messages_session_id', 'messages', ['session_id'], unique=False)
    op.create_index('idx_messages_user_id', 'messages', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('personality_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('session_metadata', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('message_count >= 0', name='chk_session_message_count'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_created_at', 'sessions', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_sessions_personality_id', 'sessions', ['personality_id'], unique=False)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_sessions_user_personality', 'sessions', ['user_id', 'personality_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_metadata', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('user', 'admin')", name='chk_user_role'),
    sa.CheckConstraint("status IN ('active', 'inactive', 'suspended')", name='chk_user_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_status', table_name='users', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('users')
    op.drop_index('idx_sessions_user_personality', table_name='sessions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_sessions_user_id', table_name='sessions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_sessions_personality_id', table_name='sessions')
    op.drop_index('idx_sessions_created_at', table_name='sessions', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('sessions')
    op.drop_index('idx_messages_user_id', table_name='messages')
    op.drop_index('idx_messages_session_id', table_name='messages')
    op.drop_index('idx_messages_session_created', table_name='messages', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_messages_created_at', table_name='messages', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('messages')
    op.drop_index('idx_audit_user_id', table_name='audit_events')
    op.drop_index('idx_audit_request_id', table_name='audit_events')
    op.drop_index('idx_audit_event_type', table_name='audit_events')
    op.drop_index('idx_audit_created_at', table_name='audit_events', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('audit_events')
    # ### end Alembic commands ###
